# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Amitakhya Phukan <aphukan@fedoraproject.org>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh.master.python-meh.as\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-09-10 09:05+0530\n"
"Last-Translator: Amitakhya Phukan <aphukan@fedoraproject.org>\n"
"Language-Team: Assamese <kde-i18n-doc@lists.kde.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Lokalize 0.2\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "ডাম্প লিখা হৈছে"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr ""
"ত্ৰুটিৰ তথ্য বিশিষ্ট নথিপত্ৰ সফলতাৰে সৈতে ডিস্কে লিখা হৈছে ।  প্ৰোগ্ৰামৰ "
"পৰা বৰ্তমানে "
"প্ৰস্থান কৰা হ'ব ।"

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "ডাম্প লিখা নহয়"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "ত্ৰুটিৰ ৰিপোৰ্ট লিখিবলৈ সমস্যা হৈছে ।"

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "নেটৱৰ্ক উপলব্ধ নাই"

#: ../src/handler.py:220
msgid ""
"Cannot save a bug report since there is no active network device available."
msgstr ""
"সক্ৰিয় নেটৱৰ্ক যন্ত্ৰ উপলব্ধ নথকাৰ কাৰণে বাগ ৰিপোৰ্ট সংৰক্ষণ কৰিবলৈ ব্যৰ্থ ।"

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"bugzilla-ৰ সৈতে যোগাযোগসময়ত নিম্নলিখিত সমস্যাৰ কাৰণে বাগ প্ৰতিবেদন কৰা "
"নাযায়:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"বাগৰ কিছু ক্ষেত্ৰত ভুল তথ্য উপস্থিত থকাৰ ফলত এই বাগটি প্ৰতিবেদন কৰা সম্ভৱ "
"নহয় ।  বাগ "
"প্ৰতিবেদন কৰাৰ প্ৰোগ্ৰামত উপস্থিত ত্ৰুটিৰ ফলত সম্ভৱত এই সমস্যা দেখা দিছে:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "বাগ প্ৰতিবেদন কৰিবলৈ ব্যৰ্থ"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "বাগ প্ৰতিবেদন কৰাৰ ব্যৱস্থা সমৰ্থিত নহয়"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"আপোনাৰ ব্যৱহৃত বিতৰণ দ্বাৰা বাগ প্ৰতিবেদন কৰাৰ কোনো ব্যৱস্থা সমৰ্থিত নহয় । "
"এই "
"কাৰণে, এই ব্যতিক্ৰম এই প্ৰক্ৰিয়াত সংৰক্ষণ কৰা সম্ভৱ নহয় ।"

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "বাগ সংক্ৰান্ত তথ্য বৈধ নহয়"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr ""
"অনুগ্ৰহ কৰি বৈধ ব্যৱহাৰকৰ্তাৰ নাম, গুপ্তশব্দ আৰু বাগৰ সংক্ষিপ্ত বিৱৰণত "
"উপলব্ধ কৰক ।"

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "প্ৰৱেশ কৰিবলৈ ব্যৰ্থ"

#: ../src/savers.py:63
#, python-format
msgid ""
"There was an error logging into %s using the provided username and password."
msgstr ""
"উল্লিখিত ব্যৱহাৰকৰ্তাৰ নাম আৰু গুপ্তশব্দ সহযোগে %s-ত প্ৰৱেশ কৰিবলৈ সমস্যা ।"

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "বাগ নিৰ্মিত হৈছে"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"আপোনাৰ দ্বাৰা উপলব্ধ traceback সহ এটা নতুন বাগ নিৰ্মাণ কৰা হৈছে । অনুগ্ৰহ "
"কৰি "
"কিছু অতিৰিক্ত তথ্য যেনে, বাগ উৎপন্ন হোৱাৰ সময় সঞ্চালিত কৰ্ম, স্ক্ৰিন-ছট আৰু "
"অন্যান্য "
"প্ৰয়োজনীয় সামগ্ৰী এই বাগত অন্তৰ্ভুক্ত কৰক:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "বাগ উন্নত কৰা হৈছে"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"এই তথ্য বিশিষ্ট এটা বাগ বৰ্তমানে উপস্থিত আছে ।  সংশ্লিষ্ট বাগৰ অনুলিপি "
"প্ৰাপকৰ "
"তালিকাত আপোনাৰ হিচাপ যোগ কৰা হৈছে আৰু আপোনাৰ দ্বাৰা উপলব্ধ traceback এটা "
"বিৱৃতি ৰূপে সংযোজন কৰা হৈছে ।  অনুগ্ৰহ কৰি নিম্নলিখিত বাগত অতিৰিক্ত তথ্য "
"যোগ "
"কৰক:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "ডিবাগ কৰক (_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "প্ৰস্থান (_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr ""
"ব্যৱস্থা নকৰা এটা ব্যতিক্ৰম উৎপন্ন হৈছে ।  এইটো সম্ভৱতঃ এটা বাগ ।  অনুগ্ৰহ "
"কৰি, "
"ব্যতিক্ৰমৰ বিৱৰণৰ এটা প্ৰতিলিপি সংৰক্ষণ কৰক আৰু এটা বাগ প্ৰতিবেদন কৰক ।"

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "তথ্য"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "বিৱৰণ (_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "বাগৰ বিৱৰণ (_d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "লক্ষ্য নথিপত্ৰ (_f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"স্থানীয় সংগ্ৰহস্থল\n"
"Bugzilla\n"
"দূৰবৰ্তী সেৱক (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "traceback-ৰ তথ্য সংৰক্ষণৰ বাবে অনুগ্ৰহ কৰি এটা স্থান নিৰ্বাচন কৰক ।"

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "সংৰক্ষণ কৰক"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "এটা নথিপত্ৰ নিৰ্বাচন কৰক"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "গৃহস্থ (host:port) (_H)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "গুপ্তশব্দ (_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "ব্যৱহাৰকৰ্তাৰ নাম (_U)"

