# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Amitakhya Phukan <aphukan@fedoraproject.org>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh.master.python-meh.as\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-09-22 16:56+0530\n"
"Last-Translator: \n"
"Language-Team: Assamese <>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Lokalize 0.2\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "ডাম্প লিখা হ'ল  "

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr ""
"ভুলৰ নথিপত্ৰক সফলভাবে ডিষ্কলৈ লিখা গৈছে । কাৰ্য্যক্ৰম এতিয়া বাহিৰ হ'ব ।"

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "ডাম্প লিখা ন'গ'ল"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "ভুলৰ প্ৰতিবেদন লিখোঁতে ভুল হৈছে ।     "

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "নে'টৱৰ্ক নাই  "

#: ../src/handler.py:220
msgid ""
"Cannot save a bug report since there is no active network device available."
msgstr ""
"সক্ৰিয় নে'টৱৰ্ক যন্ত্ৰ নথকাৰ কাৰণে বাগ প্ৰতিবেদন ৰক্ষা কৰিব পৰা ন'গ'ল ।     "
"      "

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"bugzilla ৰ সৈতে কথা পাতোঁতে হোৱা এই ভুলৰ কাৰণে আপোনাৰ বাগ প্ৰতিবেদন কৰিব "
"পৰা ন'গ'ল:\n \n %s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"বাগৰ ক্ষেত্ৰত থকা বেয়া তথ্যৰ কাৰণে আপোনাৰ বাগৰ প্ৰতিবেদন কৰিব পৰা ন'গ'ল । "
"এইটো অতি সম্ভৱ বাগ প্ৰতিবেদন অনুপ্ৰয়োগত ভুল:\n \n %s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "বাত প্ৰতিবেদন কৰিব নোৱাৰি   "

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "বাগ প্ৰতিবেদন কৰা অসমৰ্থিত     "

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"আপোনাৰ বিতৰণে বাগ প্ৰতিবেদন কৰাৰ প্ৰণালীৰ সমৰ্থন নিদিয়ে, সেইকাৰণে আপুনি এই "
"ধৰণে এই অব্যাহতি ৰক্ষা কৰিব নোৱাৰে ।স"

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "অবৈধ বাগৰ তথ্য    "

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr ""
"অনুগ্ৰহ কৰি এটা বৈধ ব্যৱহাৰকৰ্তাৰ নাম, গুপ্তশব্দ, আৰু সৰুকৈ বাগৰ বিৱৰণ দিয়ক "
"।"

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "প্ৰৱেশ কৰিব পৰা নাই  "

#: ../src/savers.py:63
#, python-format
msgid ""
"There was an error logging into %s using the provided username and password."
msgstr ""
"দিয়া ব্যৱহাৰকৰ্তাৰ নাম আৰু গুপ্তশব্দৰে %s ত প্ৰৱেশ কৰোঁতে এটা ভুল হৈছে ।    "

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "বাগ সৃষ্টি কৰা হৈছে  "

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"আপুনি দিয়া ট্ৰেচবেক লগ লগাই এটা নতুন বাগ সৃষ্টি কৰা হৈছে । অনুগ্ৰহ কৰি "
"অতিৰিক্ত তথ্য যেনে বাগ পাওঁতে আপুনি কি কৰি আছিলে, স্ক্ৰীনছ'ট, আৰু যি কোনো "
"উপকাৰী তথ্য আপুনি এই বাগত যোগ কৰিব পাৰিব:\n \n %s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "বাগ উন্নত কৰা হ'ল   "

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"আপুনি দিয়া তথ্যৰে এটা বাগ ইতিমধ্যে আছে । আপোনাৰ হিচাপক CC তালিকালৈ যোগ কৰা "
"হৈছে আৰু আপোনাৰ ট্ৰেচবেকক মন্তব্য হিচাপে যোগ কৰা হৈছে । এই বাগত আৰু অধিক "
"বিৱৰণৰ তথ্য দিয়ক:\n \n %s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "ডিবাগ  (_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "প্ৰস্থান (_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr ""
"এটা অপ্ৰত্যাশিত অব্যাহতি হৈছে । এইটো অতি সম্ভৱ এটা বাগ । বিস্তৃত অব্যাহতিৰ "
"এটা নকল ৰক্ষা কৰক আৰু বাগ প্ৰতিবেদন কৰক ।"

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "তথ্য"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "বিৱৰণ (_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "বাগৰ বিৱৰণ  (_d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "লক্ষ্য নথিপত্ৰ (_f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"স্থানীয় ভঁৰাল \n Bugzilla\n"
"দূৰৰ সেৱক (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "আপোবাৰ ট্ৰেচবেক ৰক্ষা কৰিবলৈ এটা গন্তব্য বাচি লওক ।"

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "ৰক্ষা কৰক "

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "এটা নথিপত্ৰ বাচি লওক   "

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "গৃহস্থ (host:port) (_H)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "গুপ্তশব্দ (_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "ব্যৱহাৰকৰ্তাৰ নাম  (_U)"

